/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.BarangController;
import Controller.KategoriController;
import Model.Barang;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class BarangView extends javax.swing.JFrame {
    private BarangController barangController;
    private KategoriController kategoriController;
    /**
     * Creates new form BarangView
     */
    public BarangView() {
        initComponents();
        this.barangController = new BarangController();
        this.kategoriController = new KategoriController();
        
        loadDataBarang();
    }
    
    private void loadDataBarang() {
        DefaultTableModel model = (DefaultTableModel) tabelBarang.getModel();
        model.setRowCount(0); // kosongkan isi tabel sebelum menambah data baru

        List<Barang> listBarang = barangController.tampilkanSemua();
        for (Barang b : listBarang) {
            Object[] row = {
                b.getIdBarang(), 
                b.getNamaBarang(), 
                b.getIdKategori(),
                b.getStok(), 
                b.getHargaBeli(),
                b.getHargaJual()
            };
            model.addRow(row);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelBarang = new javax.swing.JTable();
        tombolTambahBarang = new javax.swing.JButton();
        tombolHapusBarang = new javax.swing.JButton();
        tombolEditBarang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nama", "Kategori", "Stok", "Harga Beli", "Harga Jual"
            }
        ));
        jScrollPane1.setViewportView(tabelBarang);

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        tombolTambahBarang.setText("Tambah Barang");
        tombolTambahBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolTambahBarangActionPerformed(evt);
            }
        });

        tombolHapusBarang.setText("Hapus Barang");
        tombolHapusBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolHapusBarangActionPerformed(evt);
            }
        });

        tombolEditBarang.setText("Edit Barang");
        tombolEditBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolEditBarangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tombolTambahBarang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tombolHapusBarang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tombolEditBarang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(tombolTambahBarang)
                        .addGap(37, 37, 37)
                        .addComponent(tombolHapusBarang)
                        .addGap(38, 38, 38)
                        .addComponent(tombolEditBarang)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tombolTambahBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolTambahBarangActionPerformed
        // TODO add your handling code here:
        FormTambah formTambah = new FormTambah(); // dialog modal
        formTambah.setVisible(true);

        // Setelah form ditutup, reload data ke tabel
        formTambah.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                loadDataBarang(); // ini baru dipanggil saat formTambah ditutup
            }
        });
    }//GEN-LAST:event_tombolTambahBarangActionPerformed

    private void tombolHapusBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolHapusBarangActionPerformed
        // TODO add your handling code here:
        int row = tabelBarang.getSelectedRow();
        if (row >= 0) {
            int confirm = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus barang ini?");
            if (confirm == JOptionPane.YES_OPTION) {
                int idBarang = (int) tabelBarang.getValueAt(row, 0); // ambil ID dari kolom pertama
                barangController.hapusBarang(idBarang);
                loadDataBarang();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih salah satu barang yang ingin dihapus.");
        }
        loadDataBarang();
    }//GEN-LAST:event_tombolHapusBarangActionPerformed

    private void tombolEditBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolEditBarangActionPerformed
        int row = tabelBarang.getSelectedRow();
        if (row >= 0) {
            int idBarang = (int) tabelBarang.getValueAt(row, 0);
            Barang barang = barangController.cariById(idBarang);
            FormEdit formEdit = new FormEdit(); // form edit
            formEdit.setBarang(barang);
            formEdit.setVisible(true);

            loadDataBarang();
        } else {
            JOptionPane.showMessageDialog(this, "Pilih barang yang ingin diedit.");
        }
        loadDataBarang();
    }//GEN-LAST:event_tombolEditBarangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BarangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BarangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BarangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BarangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BarangView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelBarang;
    private javax.swing.JButton tombolEditBarang;
    private javax.swing.JButton tombolHapusBarang;
    private javax.swing.JButton tombolTambahBarang;
    // End of variables declaration//GEN-END:variables
}
