/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.barangController;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.barang;

/**
 *
 * @author ASUS
 */
public class barangView extends javax.swing.JFrame {
    private barangController barangCont;

    /**
     * Creates new form barangView
     */
    public barangView() {
        initComponents();
        this.barangCont = new barangController();
        
        loadDataBarang();
    }
    
    private void loadDataBarang() {
        DefaultTableModel model = (DefaultTableModel) tabelBarang.getModel();
        model.setRowCount(0);

        List<barang> listBarang = barangCont.getAllBarang();
        for (barang b : listBarang) {
            Object[] row = {
                b.getIdBarang(), 
                b.getNamaKategori(),
                b.getNamaBarang(),
                b.getStok(), 
                b.getHargaJual(),
                b.getHargaBeli()
            };
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelBarang = new javax.swing.JTable();
        tombolTambahBarang = new javax.swing.JButton();
        tombolHapusBarang = new javax.swing.JButton();
        tombolEditBarang = new javax.swing.JButton();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Kategori", "Nama", "Stok", "Harga Beli", "Harga Jual"
            }
        ));
        jScrollPane2.setViewportView(tabelBarang);

        tombolTambahBarang.setText("Tambah");
        tombolTambahBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolTambahBarangActionPerformed(evt);
            }
        });

        tombolHapusBarang.setText("Hapus");
        tombolHapusBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolHapusBarangActionPerformed(evt);
            }
        });

        tombolEditBarang.setText("Edit");
        tombolEditBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolEditBarangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tombolTambahBarang)
                    .addComponent(tombolHapusBarang)
                    .addComponent(tombolEditBarang))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(tombolTambahBarang)
                .addGap(51, 51, 51)
                .addComponent(tombolHapusBarang)
                .addGap(58, 58, 58)
                .addComponent(tombolEditBarang)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tombolTambahBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolTambahBarangActionPerformed
        // TODO add your handling code here:
        FormTambah formTambah = new FormTambah(); // dialog modal
        formTambah.setVisible(true);

        formTambah.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosed(java.awt.event.WindowEvent e) {
                    loadDataBarang(); // ✅ refresh data di tabel utama
                }
            });
    }//GEN-LAST:event_tombolTambahBarangActionPerformed

    private void tombolHapusBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolHapusBarangActionPerformed
        // TODO add your handling code here:
        int row = tabelBarang.getSelectedRow();
        if (row >= 0) {
            int confirm = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus barang ini?");
            if (confirm == JOptionPane.YES_OPTION) {
                int idBarang = (int) tabelBarang.getValueAt(row, 0); // ambil ID dari kolom pertama
                barangCont.hapusBarang(idBarang);
                loadDataBarang();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih salah satu barang yang ingin dihapus.");
        }
    }//GEN-LAST:event_tombolHapusBarangActionPerformed

    private void tombolEditBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolEditBarangActionPerformed
        // TODO add your handling code here:
        int row = tabelBarang.getSelectedRow();
        if (row >= 0) {
            int idBarang = (int) tabelBarang.getValueAt(row, 0);
            barang barang = barangCont.getBarangById(idBarang);
            FormEdit formEdit = new FormEdit(); // form edit
            formEdit.setBarangDefault(barang);
            formEdit.setVisible(true);

            formEdit.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosed(java.awt.event.WindowEvent e) {
                    loadDataBarang(); // ✅ refresh data di tabel utama
                }
            });
        } else {
            JOptionPane.showMessageDialog(this, "Pilih barang yang ingin diedit.");
        }
    }//GEN-LAST:event_tombolEditBarangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(barangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(barangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(barangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(barangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new barangView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelBarang;
    private javax.swing.JButton tombolEditBarang;
    private javax.swing.JButton tombolHapusBarang;
    private javax.swing.JButton tombolTambahBarang;
    // End of variables declaration//GEN-END:variables
}
